openapi: 3.0.3
info:
  title: Advanced Todo API
  description: API for advanced todo features including recurring tasks, due dates, reminders, priorities, and tags
  version: 1.0.0
servers:
  - url: https://api.todo-platform.com/v1
    description: Production server
  - url: https://staging-api.todo-platform.com/v1
    description: Staging server

paths:
  /tasks:
    get:
      summary: List tasks with advanced filters
      description: Retrieve a list of tasks with optional filtering, sorting, and pagination
      parameters:
        - name: priority
          in: query
          description: Filter by priority level
          schema:
            type: string
            enum: [low, medium, high, urgent]
        - name: tag
          in: query
          description: Filter by tag (can be used multiple times)
          schema:
            type: string
        - name: due_date_from
          in: query
          description: Filter tasks with due date on or after this date
          schema:
            type: string
            format: date-time
        - name: due_date_to
          in: query
          description: Filter tasks with due date on or before this date
          schema:
            type: string
            format: date-time
        - name: status
          in: query
          description: Filter by task status
          schema:
            type: string
            enum: [pending, in-progress, completed]
        - name: search
          in: query
          description: Full-text search in task title and description
          schema:
            type: string
        - name: sort_by
          in: query
          description: Field to sort by
          schema:
            type: string
            enum: [created_at, due_date, priority, title]
        - name: sort_order
          in: query
          description: Sort order
          schema:
            type: string
            enum: [asc, desc]
            default: asc
        - name: page
          in: query
          description: Page number for pagination
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: Number of items per page
          schema:
            type: integer
            default: 20
            maximum: 100
      responses:
        '200':
          description: Successful response with tasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      summary: Create a new task with advanced features
      description: Create a new task with optional due date, priority, tags, and recurrence rules
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /tasks/{taskId}:
    get:
      summary: Get a specific task
      description: Retrieve a specific task by ID
      parameters:
        - name: taskId
          in: path
          required: true
          description: Unique identifier for the task
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response with task details
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Task'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'

    put:
      summary: Update a task
      description: Update an existing task with advanced features
      parameters:
        - name: taskId
          in: path
          required: true
          description: Unique identifier for the task
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete a task
      description: Delete an existing task
      parameters:
        - name: taskId
          in: path
          required: true
          description: Unique identifier for the task
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Task deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /task-templates:
    post:
      summary: Create a recurring task template
      description: Create a template for generating recurring tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskTemplateRequest'
      responses:
        '201':
          description: Task template created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/TaskTemplate'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /reminders:
    get:
      summary: List scheduled reminders
      description: Retrieve a list of scheduled reminders
      parameters:
        - name: task_id
          in: query
          description: Filter by task ID
          schema:
            type: string
            format: uuid
        - name: is_sent
          in: query
          description: Filter by sent status
          schema:
            type: boolean
        - name: scheduled_after
          in: query
          description: Filter by scheduled time after this date
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Successful response with reminders
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ScheduledReminder'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - status
        - priority
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the task
        title:
          type: string
          maxLength: 255
          description: Task title
        description:
          type: string
          description: Optional task description
        status:
          type: string
          enum: [pending, in-progress, completed]
          description: Current status of the task
        priority:
          type: string
          enum: [low, medium, high, urgent]
          description: Priority level of the task
        due_date:
          type: string
          format: date-time
          nullable: true
          description: Due date and time for the task
        tags:
          type: array
          items:
            type: string
            maxLength: 50
          maxItems: 10
          description: Tags associated with the task
        recurrence_rule:
          type: string
          nullable: true
          description: RFC 5545 recurrence rule for recurring tasks
        parent_task_id:
          type: string
          format: uuid
          nullable: true
          description: ID of the parent task for recurring instances
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
        completed_at:
          type: string
          format: date-time
          nullable: true
          description: Completion timestamp

    CreateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 255
        description:
          type: string
        priority:
          type: string
          enum: [low, medium, high, urgent]
          default: medium
        due_date:
          type: string
          format: date-time
        tags:
          type: array
          items:
            type: string
            maxLength: 50
          maxItems: 10
        recurrence_rule:
          type: string
          description: RFC 5545 recurrence rule for recurring tasks

    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
        description:
          type: string
        status:
          type: string
          enum: [pending, in-progress, completed]
        priority:
          type: string
          enum: [low, medium, high, urgent]
        due_date:
          type: string
          format: date-time
        tags:
          type: array
          items:
            type: string
            maxLength: 50
          maxItems: 10
        recurrence_rule:
          type: string
          description: RFC 5545 recurrence rule for recurring tasks

    TaskTemplate:
      type: object
      required:
        - id
        - base_task_id
        - recurrence_rule
        - created_at
        - updated_at
        - is_active
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the template
        base_task_id:
          type: string
          format: uuid
          description: ID of the base task to use as template
        recurrence_rule:
          type: string
          description: RFC 5545 recurrence rule
        ends_on:
          type: string
          format: date-time
          nullable: true
          description: Date when recurrence should stop
        occurrence_count:
          type: integer
          nullable: true
          description: Maximum number of occurrences
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
        is_active:
          type: boolean
          description: Whether the template is currently active

    CreateTaskTemplateRequest:
      type: object
      required:
        - base_task_id
        - recurrence_rule
      properties:
        base_task_id:
          type: string
          format: uuid
          description: ID of the base task to use as template
        recurrence_rule:
          type: string
          description: RFC 5545 recurrence rule
        ends_on:
          type: string
          format: date-time
          description: Date when recurrence should stop
        occurrence_count:
          type: integer
          description: Maximum number of occurrences
        is_active:
          type: boolean
          default: true
          description: Whether the template should be active

    ScheduledReminder:
      type: object
      required:
        - id
        - task_id
        - scheduled_time
        - is_sent
        - created_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the reminder
        task_id:
          type: string
          format: uuid
          description: ID of the associated task
        user_id:
          type: string
          format: uuid
          description: ID of the user who owns the task
        scheduled_time:
          type: string
          format: date-time
          description: When the reminder should be sent
        notification_method:
          type: string
          enum: [email, push, sms]
          default: push
          description: Method of notification
        is_sent:
          type: boolean
          description: Whether the reminder has been sent
        sent_at:
          type: string
          format: date-time
          nullable: true
          description: When the reminder was sent
        created_at:
          type: string
          format: date-time
          description: Creation timestamp

    Pagination:
      type: object
      required:
        - page
        - limit
        - total
        - total_pages
      properties:
        page:
          type: integer
          description: Current page number
        limit:
          type: integer
          description: Number of items per page
        total:
          type: integer
          description: Total number of items
        total_pages:
          type: integer
          description: Total number of pages

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Additional error details

  responses:
    BadRequest:
      description: Bad request - invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized - authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication

security:
  - bearerAuth: []